# Change baseurl before deploy
baseurl: https://MysticalDream.github.io/
languageCode: zh-cn
theme: hugo-theme-stack
paginate: 5
title: 幻梦的博客


enableEmoji: true # 允许使用 Emoji 表情
buildDrafts: false
buildFuture: false
buildExpired: false
enableRobotsTXT: true
minify:
  disableXML: true

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage: zh-cn

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: true
# Change it to your Disqus shortname before using
# disqusShortname: hugo-theme-stack

pygmentsUseClasses: true