# Configure main menu and social menu
# main:
#   - identifier: home
#     name: Home
#     url: /
#     params:
#       icon: home
#       newtab: true

social:
  - identifier: github
    name: GitHub
    url: https://github.com/MysticalDream
    params:
      icon: brand-github
  - identifier: rss
    name: RSS
    url: https://MysticalDream.github.io/index.xml
    params:
      icon: rss
